### ISSUE TITLE
How to use an external map with xodr file without having to build CARLA from source

### ISSUE THREAD

**Issue by Anhar2** [carla-simulator/scenario_runner#1078]
**Describe our question or idea**
A clear and concise description.

I have created and run a Python-defined scenario on a regular CARLA map, but I need to get this scenario run on an external map which I have its xodr file, I noticed that the documentations mentioned that this can be done if I had built CARLA from source, is there any other way? Please note that the scenario is defined by Python not OSC

 - OS: [e.g. Ubuntu 2004]
 - CARLA 0.9.13 with leaderboard2
 - Python 3.8
 - Version  0.9.13

Thanks in advance

**Comment by glopezdiest** [comment]
Hey @Anhar2, you can always use the [OpenDRIVE standalone mode](https://carla.readthedocs.io/en/0.9.11/adv_opendrive/#run-a-standalone-map) to run a simulation using the xodr map. So modify ScenarioRunner to load the generated xodr map, instead of the normal map.

Closing the issue as its resolved, but feel free to reopen it other questions arise
