### ISSUE TITLE
Failed to run challenge_evaluator_routes.py with HumanAgent

### ISSUE THREAD

**Issue by linxigjs** [carla-simulator/scenario_runner#400]
When i run challenge_evaluator_routes.py as Docs/challenge_evaluation.md says, 
`python srunner/challenge/challenge_evaluator_routes.py --scenarios=${ROOT_SCENARIO_RUNNER}/srunner/challenge/all_towns_traffic_scenarios1_3_4.json --agent=${ROOT_SCENARIO_RUNNER}/srunner/challenge/autoagents/HumanAgent.py
`
there is a black window named "Human Agent" appears and disappears after a while, then repeatedly appear and disappears. What's wrong with that? What should i do to solve it?
carla version: v0.9.5, scenerio runner version: v0.9.5.1
![选区_014](https://user-images.githubusercontent.com/24429575/68288143-d4ab3e00-00be-11ea-8981-a3fac33b55fb.png)

**Comment by ZTige** [comment]
I have the same issue, have you figured it out? Thanks

**Comment by Yougmark** [comment]
I am able to run HumanAgent with the master branch and my own small fix #408.
It's pretty cool.  Don't forget to turn on the debug option for viewing the waypoints visualization.

**Comment by linxigjs** [comment]
> I am able to run HumanAgent with the master branch and my own small fix #408.
> It's pretty cool. Don't forget to turn on the debug option for viewing the waypoints visualization.

Thank you for your help, but my problem is still unresolved. And in my test, no exception threw, which is different from your #408

**Comment by Yougmark** [comment]
@linxigjs Are you still using 0.9.5 scenario runner? I had issues with synchronous mode with older version (0.9.6 I think).  Probably the problem was there in 0.9.5 too.  You can try disabling synchronous mode in `challenge_evaluator_routes.py`.  I remember it was running forever in a while loop waiting for the sensors to be ready or actors to be created (not sure which one).

Anyway, try tracing down the `challenge_evaluator_routes.py` script and see where it gets stuck.

**Comment by linxigjs** [comment]
Thanks for your answer @Yougmark , I will figure it out once I have the time...

**Comment by glopezdiest** [comment]
Closing this as it is no longer relevant to current Scenario Runner. Feel free to reopen it if that isn't the case
