### ISSUE TITLE
No output file generated for openScenario

### ISSUE THREAD

**Issue by TeeManiac** [carla-simulator/scenario_runner#682]
While running openScenario based scenarios in scenario runner, the result files are not getting generated. Tried the following commands:
python scenario_runner.py --openscenario srunner\examples\LaneChangeSimple.xosc  --reloadWorld --output --json and also tried
python scenario_runner.py --openscenario srunner\examples\LaneChangeSimple.xosc  --reloadWorld --output --file

A file named CARLA of size 0kb is getting created everytime I try with these commands. The result files are getting generated for basic scenarios but not for openscenario. Is result file not supported for openScenario?

As shown in the screenshot, the json files are generated foe basic_scenario whereas the file named CARLA is getting generated for openscenario execution.

**Desktop
![Screenshot from 2020-11-10 22-18-40](https://user-images.githubusercontent.com/30982320/98704883-2a39bb00-23a3-11eb-9da3-f627014c2d90.png)
:**

OS: [Windows 10]
CARLA Version [CARLA 0.9.10]
Python version [3.9.0] [Only python 3.9 is installed in system]
Scenario_runner Version [0.9.10]

**Comment by glopezdiest** [comment]
Hey @TeeManiac, sorry for the delay. Checking the issues I thought this one was already solved. Did you manage to solve it? I just checked and it's working fine for me. A file named *CARLA:CyclistCrossing2020-11-18-09-57-58.txt* was created, with all the info needed.

However, I am working on Ubuntu, and not Windows so that might be an issue (maybe the *:* have a specific meaning there?). If you haven't solved it yet please try the following

1. Change the starting name of the OpenScenario file from *CARLA:* to *CARLA_* (1st line of the *.xosc*)
2. Go to *srunner/scenarioconfigs/openscenario_configurations.py and change the check at *_set_scenario_name()* for *CARLA_*

![image](https://user-images.githubusercontent.com/58212725/99509574-36ff7580-2986-11eb-8145-1027ea94d744.png)
 
Let me know if this fixes it, because we might want to change that part if it is a Windows related problem

**Comment by TeeManiac** [comment]
> Hey @TeeManiac, sorry for the delay. Checking the issues I thought this one was already solved. Did you manage to solve it? I just checked and it's working fine for me. A file named _CARLA:CyclistCrossing2020-11-18-09-57-58.txt_ was created, with all the info needed.
> 
> However, I am working on Ubuntu, and not Windows so that might be an issue (maybe the _:_ have a specific meaning there?). If you haven't solved it yet please try the following
> 
> 1. Change the starting name of the OpenScenario file from _CARLA:_ to _CARLA__ (1st line of the _.xosc_)
> 2. Go to *srunner/scenarioconfigs/openscenario_configurations.py and change the check at __set_scenario_name()_ for _CARLA__
> 
> ![image](https://user-images.githubusercontent.com/58212725/99509574-36ff7580-2986-11eb-8145-1027ea94d744.png)
> 
> Let me know if this fixes it, because we might want to change that part if it is a Windows related problem

I fixed it by replacing ":" with "" in config_name and its working now.

**Comment by fabianoboril** [comment]
@TeeManiac Thanks for this info. Maybe we should just remove this "CARLA:" for the output file, as it is more or less just an internal way of handling the different coordinate systems.

**Comment by TeeManiac** [comment]
> @TeeManiac Thanks for this info. Maybe we should just remove this "CARLA:" for the output file, as it is more or less just an internal way of handling the different coordinate systems.

@fabianoboril Yes, I too think so as the json file for basic scenario just has the Scenario name + current time for the json file name.
